### ISSUE TITLE
TypeInitializationException for eifokk in .Net 5 Blazor App

### ISSUE THREAD

**Issue by ahawes-clarity** [iron-software/Iron-Barcode-Reading-Barcodes-In-CSharp#8]
I am trying to trial the use of IronBarcode in a .Net 5 Blazor Web Assembly App and I am getting this exception:

System.TypeInitializationException: The type initializer for 'IronBarCode.BarcodeReader' threw an exception. ---> System.TypeInitializationException: The type initializer for 'eifokk' threw an exception. ---> System.InvalidProgramException at IronBarCode.Extensions.qgnwoy.eifokk..cctor() --- End of inner exception stack trace --- at IronBarCode.Extensions.qgnwoy.etlamw(Int32 bnyu) at IronBarCode.BarcodeReader..cctor()

Here is my code:
            var format = "image/png";
            var imageFile = await e.File.RequestImageFileAsync(format, 640, 480);

            await using var fileStream = imageFile.OpenReadStream(maxFileSize);
            var Result = BarcodeReader.QuicklyReadOneBarcode(fileStream, BarcodeEncoding.Code39, true);

**Comment by darren-iron** [comment]
Blazor web assembly is designed to work on the client web browser. IronBarcode is developed to work on the server-side, so you would need to create a Blazor web assembly project with .NET Core Hosted app.
This creates a server-side project and client-side project. Use IronBarcode in the server-side project.

![24ef0b2745892d9a272adade184afac2](https://user-images.githubusercontent.com/73033617/116521665-76030100-a8fe-11eb-8838-532ad881e0d0.png)

**Comment by ahawes-clarity** [comment]
Thanks, but we went with ZXing instead. It met our needs.
